# Generated by Django 6.1.1 on 2026-09-16 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoritelocation',
            constraint=models.UniqueConstraint(fields=('user', 'latitude', 'longitude'), name='unique_user_favorite_location'),
        ),
    ]
